project:
 type: website

website:
 title: "another_quarto"
 navbar:
   left:
     - href: index.qmd
       text: Home
     - about.qmd

format:
 html:
   theme: jekyll-theme-minimal
   css: styles.css
   toc: true

editor: visual
